<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5914" started-at="2020-09-02T05:09:12Z" finished-at="2020-09-02T05:09:17Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="5914" started-at="2020-09-02T05:09:12Z" finished-at="2020-09-02T05:09:17Z">
      <class name="TestCases.EmployeeTest">
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="BeforeSuite" is-config="true" duration-ms="10" started-at="2020-09-02T10:39:11Z" finished-at="2020-09-02T10:39:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="BeforeClass" is-config="true" duration-ms="4" started-at="2020-09-02T10:39:12Z" finished-at="2020-09-02T10:39:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="PASS" signature="BeforeMethod(java.lang.reflect.Method)[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="BeforeMethod" is-config="true" duration-ms="1" started-at="2020-09-02T10:39:12Z" finished-at="2020-09-02T10:39:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.EmployeeTest.Scenario1()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="Scenario1()[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="Scenario1" duration-ms="3743" started-at="2020-09-02T10:39:12Z" finished-at="2020-09-02T10:39:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario1 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="AfterMethod" is-config="true" duration-ms="346" started-at="2020-09-02T10:39:15Z" finished-at="2020-09-02T10:39:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod(java.lang.reflect.Method)[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2020-09-02T10:39:16Z" finished-at="2020-09-02T10:39:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.EmployeeTest.Scenario2()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="Scenario2()[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="Scenario2" duration-ms="1621" started-at="2020-09-02T10:39:16Z" finished-at="2020-09-02T10:39:17Z">
          <exception class="io.restassured.path.json.exception.JsonPathException">
            <message>
              <![CDATA[Failed to parse the JSON document]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
	at TestCases.EmployeeTest.Scenario2(EmployeeTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- io.restassured.path.json.exception.JsonPathException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario2 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:TestCases.EmployeeTest@4c70fda8]" name="AfterMethod" is-config="true" duration-ms="173" started-at="2020-09-02T10:39:17Z" finished-at="2020-09-02T10:39:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
      </class> <!-- TestCases.EmployeeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
